name: gaze
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.9.1
  chewie: ^1.7.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.7.0
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  intl: ^0.18.1
  lottie: ^2.6.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  http: ^0.13.5
  http_interceptor: ^1.0.1
  logger: ^1.1.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  transparent_image: ^2.0.1
  flutter_native_splash: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.12.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_storage_mocks: ^0.6.1
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "asset/images/gaze-icon.png"
  adaptive_icon_foreground: "asset/images/adaptive-logo.png"
  adaptive_icon_background: "#111822"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#111822"
  image: "asset/images/gaze-logo.png"
  android_12:
    color: "#111822"
    image: "asset/images/gaze-logo.png"

flutter:

  uses-material-design: true

  assets:
    - asset/lottie/
    - asset/images/

  fonts:
    - family: Aeonik
      fonts:
        - asset: asset/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: asset/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: asset/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: asset/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: asset/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: asset/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Satisfy
      fonts:
        - asset: asset/fonts/satisfy/Satisfy-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: asset/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: asset/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: asset/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: asset/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: asset/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800